"""initial_schema

Revision ID: 373326eef00d
Revises: 
Create Date: 2026-04-19 11:10:32.493643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373326eef00d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_order_history_id'), 'order_history', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_configs_id'), 'strategy_configs', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_states_id'), 'strategy_states', ['id'], unique=False)
    op.create_index(op.f('ix_trade_logs_id'), 'trade_logs', ['id'], unique=False)
    op.alter_column('user_settings', 'kite_api_secret',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('zerodha_sessions', 'access_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_zerodha_sessions_id'), 'zerodha_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zerodha_sessions_id'), table_name='zerodha_sessions')
    op.alter_column('zerodha_sessions', 'access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.alter_column('user_settings', 'kite_api_secret',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_trade_logs_id'), table_name='trade_logs')
    op.drop_index(op.f('ix_strategy_states_id'), table_name='strategy_states')
    op.drop_index(op.f('ix_strategy_configs_id'), table_name='strategy_configs')
    op.drop_index(op.f('ix_order_history_id'), table_name='order_history')
    # ### end Alembic commands ###
